services:
  - type: web
    name: agente-mcp-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run agente_rag_app3.py --server.port=10000 --server.enableCORS=false
    envVars:
      - key: GROQ_API_KEY
        value: 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   # ou deixe em branco e configure via painel do Render
